/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AircraftRow: typeof import('./src/components/Authenticated/AircraftRow.vue')['default']
    AppDialog: typeof import('./src/components/AppDialog.vue')['default']
    AppDivider: typeof import('./src/components/AppDivider.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppOffline: typeof import('./src/components/Authenticated/AppOffline.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    CurrentFlights: typeof import('./src/components/Authenticated/CurrentFlights.vue')['default']
    DisplayRows: typeof import('./src/components/Authenticated/DisplayRows.vue')['default']
    ExpandAll: typeof import('./src/components/Authenticated/ExpandAll.vue')['default']
    FlightRoute: typeof import('./src/components/Authenticated/FlightRoute.vue')['default']
    ForceUpdate: typeof import('./src/components/Authenticated/ForceUpdate.vue')['default']
    PiInfo: typeof import('./src/components/Authenticated/PiInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleScreen: typeof import('./src/components/Authenticated/ToggleScreen.vue')['default']
  }
}
